# Scripts producing tables and figures in li_et_al_2023_natcom
# Xue (Michelle) Li, xue.li@pnnl.gov
# Sept, May 2023

require(raster)
require(sf)
require(fs)
require(tmap)
require(tidyverse)
require(ggpubr)
require(FedData)
require(foreach)

# Set up folders
base_folder = "../" # assuming working directory is set to the source file location
plot_folder = "./"

# Global settings and variables
tmap_options(check.and.fix = TRUE)
domain = st_read(path(base_folder,"data/support/domain.shp"))
huc12 = st_read(path(base_folder,"data/support/huc12.shp"))
states = st_read(path(base_folder,"data/support/cb_2018_us_state_5m.shp"))
land = st_read(path(base_folder,"data/support/Political_Boundaries__Area_.shp"))%>% st_transform(st_crs(states))
plot_bbox = st_bbox(huc12)
plot_size = 2.5 # in inches with default dpi as 300

################################################################
# Precipitation
################################################################
# Total precipitation in present scenario
total_present = raster(path(base_folder,"data/prcp/present_prcp_total.tif"))%>% # data generated by prcp.py
  projectRaster(crs=4269) 

# Figure 1(a)
# Plot precipitation with simulation domain
plot_domain = tm_shape(total_present,bbox=plot_bbox)+tm_raster(palette='YlGnBu',title='')+
  tm_shape(domain)+tm_borders(col="grey50")+tm_text("HUC4",size=0.5,bg.color="white",bg.alpha=0.5)+
  tm_layout(title='(a) PRCP(mm)',title.position=c('LEFT','TOP'),title.size=1,legend.position=c("RIGHT","BOTTOM"),legend.bg.color=T,legend.bg.alpha=0.5)+
  tm_grid(lines=F)
tmap_save(plot_domain,width=plot_size,height=plot_size,filename=path(plot_folder,'domain.png'))

################################################################
# Flood Characteristics
################################################################
# Domain average
# Present scenario
flood_huc4 = read_csv(path(base_folder,'data/flood/huc4/flood.csv'))
domain_avg = flood_huc4 %>% group_by(version) %>%
  summarise(h=sum(h*wet)*100/sum(wet),# m to cm
            dhdt=sum(dhdt*wet)*100/sum(wet),# m/h to cm/h
            he=sum(he*wet)*100/sum(wet),# m to cm
            area=sum(wet*unit_area)) # km2
domain_avg_present = domain_avg %>% filter(version=='present')
# Table 1 - Present
print(domain_avg_present) 

# Climate contribution
domain_avg_diff = domain_avg %>% filter(version!='present') %>%
  mutate(h_diff=h-domain_avg_present$h,h_pct=h_diff*100/domain_avg_present$h,
         dhdt_diff=dhdt-domain_avg_present$dhdt,dhdt_pct=dhdt_diff*100/domain_avg_present$dhdt,
         he_diff=he-domain_avg_present$he,he_pct=he_diff*100/domain_avg_present$he,
         area_diff=area-domain_avg_present$area,area_pct=area_diff*100/domain_avg_present$area,)
# Table 1 - counterfactual columns
domain_avg_diff

# Plotting function
plotHUC12 = function(data,column_name,title,palette,breaks=NULL,labels=NULL){
  tm_shape(land,bbox=plot_bbox)+tm_fill(col="grey85")+
    tm_shape(data)+tm_fill(col=column_name,palette=palette,title='',breaks=breaks,labels=labels,showNA=F)+
    tm_shape(states)+tm_borders(col="grey50")+#tm_text("NAME",size=0.5)+
    tm_layout(title=title,title.position=c('LEFT','TOP'),title.size=1,
              legend.position=c("RIGHT","BOTTOM"),legend.bg.color=T,legend.bg.alpha=0.5)+
    tm_grid(lines=F)
}

# Convert number of pixels to areas
df_unit_area = flood_huc4 %>% dplyr::select(huc4,unit_area) %>% distinct()
calcArea = function(df,df_unit_area){
  df %>% mutate(huc4=str_sub(huc12,1,4)) %>% left_join(df_unit_area) %>%
    mutate(area=wet*unit_area)
}

# HUC12 overviews
# Present scenario
huc12_present = read_csv(path(base_folder,'data/flood/huc12/present.csv')) %>%
  mutate(pct_flood=wet/n*100) %>% calcArea(df_unit_area)
sf_huc12_present = huc12 %>% left_join(huc12_present,by='huc12')
# Figure 1(b)
plot_h_present = plotHUC12(sf_huc12_present,'h','(b) H(m)',palette='Blues',breaks=c(0,1,2,3,4,6))
tmap_save(plot_h_present,width=plot_size,height=plot_size,filename=path(plot_folder,'h_present.png'))
# Figure 1(c)
plot_dhdt_present = plotHUC12(sf_huc12_present,'dhdt','(c) DH/DT(m/h)',palette='Greens',breaks=c(0,0.25,0.5,0.75,1,1.5))
tmap_save(plot_dhdt_present,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_present.png'))
# Figure 1(d)
plot_he_present = plotHUC12(sf_huc12_present,'he','(d) HE(m)',palette='Purples',breaks=c(0,1,2,3,4,7))
tmap_save(plot_he_present,width=plot_size,height=plot_size,filename=path(plot_folder,'he_present.png'))
# Figure 1(e)
plot_ext_present = plotHUC12(sf_huc12_present,'pct_flood','(e) % Flooded',palette='Reds',breaks=c(0,5,10,20,30,50))
tmap_save(plot_ext_present,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_present.png'))

# Differences: Present - Past14%
diff_p14 = read_csv(path(base_folder,'data/flood/huc12/diff_p14.csv')) %>%
  mutate(pml_flood=(over-under)/n*1000,h=h*100,dhdt=dhdt*100,he=he*100,wet=over-under) %>%# convert from m to cm
  calcArea(df_unit_area)
sf_diff_p14 = huc12 %>% left_join(diff_p14,by='huc12')
# Figure 2(a)
plot_h_diff_p14 = plotHUC12(sf_diff_p14,'h','(a) \u0394H(cm)',palette='viridis',
                            breaks=c(-1,0,10,20,40,60,75),labels=c('-1-0','0-10','10-20','20-40','40-60','60-75'))
tmap_save(plot_h_diff_p14,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_p14.png'))
# Figure 2(c)
plot_dhdt_diff_p14 = plotHUC12(sf_diff_p14,'dhdt','(c) \u0394DH/DT(cm/h)',palette='inferno',
                               breaks=c(-1,0,2,4,6,10,17),labels=c('-1-0','0-2','2-4','4-6','6-10','10-17'))
tmap_save(plot_dhdt_diff_p14,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_p14.png'))
# Figure 2(e)
plot_he_diff_p14 = plotHUC12(sf_diff_p14,'he','(e) \u0394HE(cm)',palette='magma',
                             breaks=c(0,10,20,40,60,80,200),labels=c('0-10','10-20','20-40','40-60','60-80','80-200'))
tmap_save(plot_he_diff_p14,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_p14.png'))
# Figure 2(g)
plot_ext_diff_p14 = plotHUC12(sf_diff_p14,'pml_flood','(g) \u0394\u2030Flooded',palette='plasma',
                              breaks=c(-2,0,5,10,20,40,90),labels=c('-2-0','0-5','5-10','10-20','20-40','40-90'))
tmap_save(plot_ext_diff_p14,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_p14.png'))

# Differences: Present - Past7%
diff_p7 = read_csv(path(base_folder,'data/flood/huc12/diff_p7.csv')) %>%
  mutate(pml_flood=(over-under)/n*1000,h=h*100,dhdt=dhdt*100,he=he*100,wet=over-under) %>%# convert from m to cm
  calcArea(df_unit_area)
sf_diff_p7 = huc12 %>% left_join(diff_p7,by='huc12')
# Figure S1(a)
plot_h_diff_p7 = plotHUC12(sf_diff_p7,'h','(a) \u0394H(cm)',palette='viridis',
                           breaks=c(-4,0,5,10,20,30,40),labels=c('-4-0','0-5','5-10','10-20','20-30','30-40'))
tmap_save(plot_h_diff_p7,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_p7.png'))
# Figure S1(c)
plot_dhdt_diff_p7 = plotHUC12(sf_diff_p7,'dhdt','(c) \u0394DH/DT(cm/h)',palette='inferno',
                              breaks=c(-1,0,1,2,3,5,9),labels=c('-1-0','0-1','1-2','2-3','3-5','5-9'))
tmap_save(plot_dhdt_diff_p7,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_p7.png'))
# Figure S1(e)
plot_he_diff_p7 = plotHUC12(sf_diff_p7,'he','(e) \u0394HE(cm)',palette='magma',
                            breaks=c(-4,5,10,20,30,40,170),labels=c('-4-5','5-10','10-20','20-30','30-40','40-170'))
tmap_save(plot_he_diff_p7,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_p7.png'))
# Figure S1(g)
plot_ext_diff_p7 = plotHUC12(sf_diff_p7,'pml_flood','(g) \u0394\u2030Flooded',palette='plasma',
                             breaks=c(-2.5,0,2.5,5,10,20,55),labels=c('-2.5-0','0-2.5','2.5-5','5-10','10-20','20-55'))
tmap_save(plot_ext_diff_p7,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_p7.png'))

# Differences: Future14% - Present
diff_f14 = read_csv(path(base_folder,'data/flood/huc12/diff_f14.csv')) %>%
  mutate(pml_flood=(over-under)/n*1000,h=h*100,dhdt=dhdt*100,he=he*100,wet=over-under) %>%# convert from m to cm
  calcArea(df_unit_area)
sf_diff_f14 = huc12 %>% left_join(diff_f14,by='huc12')
# Figure S2(a)
plot_h_diff_f14 = plotHUC12(sf_diff_f14,'h','(a) \u0394H(cm)',palette='viridis',
                            breaks=c(-16,0,10,20,40,60,82),labels=c('-16-0','0-10','10-20','20-40','40-60','60-82'))
tmap_save(plot_h_diff_f14,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_f14.png'))
# Figure S2(c)
plot_dhdt_diff_f14 = plotHUC12(sf_diff_f14,'dhdt','(c) \u0394DH/DT(cm/h)',palette='inferno',
                               breaks=c(-2,0,2,4,6,10,21),labels=c('-2-0','0-2','2-4','4-6','6-10','10-21'))
tmap_save(plot_dhdt_diff_f14,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_f14.png'))
# Figure S2(e)
plot_he_diff_f14 = plotHUC12(sf_diff_f14,'he','(e) \u0394HE(cm)',palette='magma',
                             breaks=c(-16,10,20,40,60,80,84),labels=c('-16-10','10-20','20-40','40-60','60-80','80-84'))
tmap_save(plot_he_diff_f14,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_f14.png'))
# Figure S2(g)
plot_ext_diff_f14 = plotHUC12(sf_diff_f14,'pml_flood','(g) \u0394\u2030Flooded',palette='plasma',
                              breaks=c(-28,0,5,10,20,40,105),labels=c('-28-0','0-5','5-10','10-20','20-40','40-105'))
tmap_save(plot_ext_diff_f14,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_f14.png'))

# Differences: Future7% - Present
diff_f7 = read_csv(path(base_folder,'data/flood/huc12/diff_f7.csv'))%>%
  mutate(pml_flood=(over-under)/n*1000,h=h*100,dhdt=dhdt*100,he=he*100,wet=over-under) %>%# convert from m to cm
  calcArea(df_unit_area)
sf_diff_f7 = huc12 %>% left_join(diff_f7,by='huc12')
# Figure S3(a)
plot_h_diff_f7 = plotHUC12(sf_diff_f7,'h','',palette='viridis',
                           breaks=c(-21,0,5,10,20,30,46),labels=c('-21-0','0-5','5-10','10-20','20-30','30-46'))
tmap_save(plot_h_diff_f7,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_f7.png'))
# Figure S3(c)
plot_dhdt_diff_f7 = plotHUC12(sf_diff_f7,'dhdt','',palette='inferno',
                              breaks=c(-2,0,1,2,3,5,11),labels=c('-2-0','0-1','1-2','2-3','3-5','5-11'))
tmap_save(plot_dhdt_diff_f7,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_f7.png'))
# Figure S3(e)
plot_he_diff_f7 = plotHUC12(sf_diff_f7,'he','',palette='magma',
                            breaks=c(-22,5,10,20,30,40,46),labels=c('-22-5','5-10','10-20','20-30','30-40','40-46'))
tmap_save(plot_he_diff_f7,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_f7.png'))
# Figure S3(g)
plot_ext_diff_f7 = plotHUC12(sf_diff_f7,'pml_flood','(g) \u0394\u2030Flooded',palette='plasma',
                             breaks=c(-61,0,2.5,5,10,20,73),labels=c('-61-0','0-2.5','2.5-5','5-10','10-20','20-73'))
tmap_save(plot_ext_diff_f7,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_f7.png'))

# Scatter plots
plotLM = function(x,y,title){
  df = tibble(present=x,difference=y)
  m = lm(difference~present,df)
  # eq = bquote(y==.(format(unname(coef(m)[1]),digits=2))+.(format(unname(coef(m)[2]),digits=2))*x~','~
  #               R^2==.(format(summary(m)$r.squared, digits=2)))
  eq_str = str_c("y=",round(coef(m)[1],2),"+",round(coef(m)[2],2),"x\n",
                 "R^2=",round(summary(m)$r.squared, 2))
  print(eq_str)
  ggplot(df,aes(x=present,y=difference)) + 
    #geom_bin_2d()+
    geom_point(size=0.5)+
    geom_smooth(method = "lm", se=FALSE, color="steelblue", formula = y ~ x)+
    geom_text(x = 0, y = range(y)[2],label = eq_str, hjust = 0, vjust = 1, size = 3.5, col='grey30')+
    labs(title=title,x="Present scenario value",y="Difference")+ 
    theme(plot.title = element_text(size=12))
}
# Past 14%
# Figure 2(b)
plot_h_diff_p14_lm = plotLM(huc12_present$h,diff_p14$h/100,'(b) H(m)')
ggsave(plot_h_diff_p14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_p14_lm.png'))
# Figure 2(d)
plot_dhdt_diff_p14_lm = plotLM(huc12_present$dhdt,diff_p14$dhdt/100,'(d) DH/DT(m/h)')
ggsave(plot_dhdt_diff_p14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_p14_lm.png'))
# Figure 2(f)
plot_he_diff_p14_lm = plotLM(huc12_present$he,diff_p14$he/100,'(f) HE(m)')
ggsave(plot_he_diff_p14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_p14_lm.png'))
# Figure 2(h)
plot_ext_diff_p14_lm = plotLM(huc12_present$area,diff_p14$area,bquote('(h) Area Flooded ('~km^2~')'))
ggsave(plot_ext_diff_p14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_p14_lm.png'))

# Past 7%
# Figure S1(b)
plot_h_diff_p7_lm = plotLM(huc12_present$h,diff_p7$h/100,'(b) H(m)')
ggsave(plot_h_diff_p7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_p7_lm.png'))
# Figure S1(d)
plot_dhdt_diff_p7_lm = plotLM(huc12_present$dhdt,diff_p7$dhdt/100,'(d) DH/DT(m/h)')
ggsave(plot_dhdt_diff_p7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_p7_lm.png'))
# Figure S1(f)
plot_he_diff_p7_lm = plotLM(huc12_present$he,diff_p7$he/100,'(f) HE(m)')
ggsave(plot_he_diff_p7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_p7_lm.png'))
# Figure S1(h)
plot_ext_diff_p7_lm = plotLM(huc12_present$area,diff_p7$area,bquote('(h) Area Flooded ('~km^2~')'))
ggsave(plot_ext_diff_p7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_p7_lm.png'))

# Future 14%
# Figure S2(b)
plot_h_diff_f14_lm = plotLM(huc12_present$h,diff_f14$h/100,'(b) H(m)')
ggsave(plot_h_diff_f14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_f14_lm.png'))
# Figure S2(d)
plot_dhdt_diff_f14_lm = plotLM(huc12_present$dhdt,diff_f14$dhdt/100,'(d) DH/DT(m/h)')
ggsave(plot_dhdt_diff_f14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_f14_lm.png'))
# Figure S2(f)
plot_he_diff_f14_lm = plotLM(huc12_present$he,diff_f14$he/100,'(f) HE(m)')
ggsave(plot_he_diff_f14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_f14_lm.png'))
# Figure S2(h)
plot_ext_diff_f14_lm = plotLM(huc12_present$area,diff_f14$area,bquote('(h) Area Flooded ('~km^2~')'))
ggsave(plot_ext_diff_f14_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_f14_lm.png'))

# Future 7%
# Figure S2(b)
plot_h_diff_f7_lm = plotLM(huc12_present$h,diff_f7$h/100,'(b) H(m)')
ggsave(plot_h_diff_f7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'h_diff_f7_lm.png'))
# Figure S2(d)
plot_dhdt_diff_f7_lm = plotLM(huc12_present$dhdt,diff_f7$dhdt/100,'(d) DH/DT(m/h)')
ggsave(plot_dhdt_diff_f7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'dhdt_diff_f7_lm.png'))
# Figure S2(f)
plot_he_diff_f7_lm = plotLM(huc12_present$he,diff_f7$he/100,'(f) HE(m)')
ggsave(plot_he_diff_f7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'he_diff_f7_lm.png'))
# Figure S2(h)
plot_ext_diff_f7_lm = plotLM(huc12_present$area,diff_f7$area,bquote('(h) Area Flooded ('~km^2~')'))
ggsave(plot_ext_diff_f7_lm,width=plot_size,height=plot_size,filename=path(plot_folder,'ext_diff_f7_lm.png'))


################################################################
# Impact
################################################################
# Developed lands
nlcd_legend = pal_nlcd() %>% mutate(class1=as.character(ID)%>%str_sub(1,-2))
nlcd_summary = read_csv(path(base_folder,'data/impact/landcover/summary.csv'),col_types='nccfnn')%>% 
  filter(nlcd!=0) %>% mutate(area=counts*30*30*1e-9) # 1000 km2
nlcd_df = nlcd_summary %>% left_join(nlcd_legend,by=c('nlcd'='ID')) %>%
  group_by(version,threshold,class1) %>% summarize(area=sum(area)) %>% ungroup
#nlcd_df

# Table 2 line 1
nlcd_present = nlcd_df %>% filter(version=='present') %>% transmute(threshold,class1,baseline=area)
nlcd_present %>% filter(threshold==0.5,class1=='2')
nlcd_climate_change = nlcd_df %>% filter(version!='present') %>% left_join(nlcd_present) %>%
  mutate(delta=area-baseline,pct=abs(delta)*100/baseline)
nlcd_climate_change %>% filter(threshold==0.5,class1=='2')

# Population
pop_summary = read_csv(path(base_folder,'data/impact/population/summary.csv'),col_types='nccfn')
pop_df = pop_summary %>% group_by(version,threshold) %>% summarize(population=sum(pop)*1e-6) %>% ungroup
#pop_df

# Table 2 line 2
pop_present = pop_df %>% filter(version=='present')
pop_present %>% filter(threshold==0.5)
pop_climate_change = pop_df %>% filter(version!='present') %>%
  left_join(dplyr::select(pop_present,threshold,baseline=population)) %>%
  mutate(delta=population-baseline,pct=abs(delta)*100/baseline)
pop_climate_change %>% filter(threshold==0.5)

# Impact by depth
plotImpact = function(data,ylab,tag){
  version_col = c('p7'='dodgerblue2','p14'='dodgerblue2','f7'='coral2','f14'='coral2')
  version_lty = c('p7'=2,'p14'=1,'f7'=2,'f14'=1)
  version_lbl = c('f7'='Future 7%','f14'='Future 14%','p7'='Past 7%','p14'='Past 14%')
  ref = data %>% filter(version=='f7')
  output = ggplot(data)+
    geom_line(aes(x=threshold,y=pct,group=version,color=version,linetype=version))+
    geom_point(aes(x=threshold,y=pct,group=version,color=version),size=0.5)+
    scale_color_manual(values=version_col,labels=version_lbl)+
    scale_linetype_manual(values=version_lty,labels=version_lbl)+
    geom_col(data=ref,aes(x=threshold,y=baseline/.2),alpha=0.5)+
    scale_y_continuous(labels=~ .*.2,ylab,limits=c(0,32),sec.axis=sec_axis(~.,name = "|%| Change"))+
    labs(x='Depth threshold (ft)',color="Scenario",linetype="Scenario",tag=tag)
}
# Figure 3(a)
p_nlcd_depth = plotImpact(filter(nlcd_climate_change,class1=='2'),ylab='Developed land('~10^3~~km^2~')',tag='(a)')
p_nlcd_depth
# Figure 3(b)
p_pop_depth = plotImpact(pop_climate_change,ylab='Population (million)',tag='(b)')
p_pop_depth
# Figure 3 combined
ggarrange(p_nlcd_depth, p_pop_depth, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
ggsave(path(plot_folder,'impact_depth.png'),w=6,h=3)

#SVI

# background
svi_bg_df = read_csv(path(base_folder,"data/impact/population/svi_bg.csv"))%>%
  mutate(svi=factor(svi,levels=c("Lowest","Medium_low","Medium_high","Highest")))
svi_bg_huc = svi_bg_df %>% group_by(`...1`) %>% 
  mutate(pct=pop/sum(pop)*100)
pop_bg_all = sum(svi_bg_df$pop)
svi_bg_all = svi_bg_df %>% group_by(svi) %>% summarise(pop=sum(pop))%>% 
  mutate(pct=pop/pop_bg_all*100)

# flood exposure
svi_df = read_csv(path(base_folder,"data/impact/population/svi.csv"))%>%
  mutate(svi=factor(svi,levels=c("Lowest","Medium_low","Medium_high","Highest")))
svi_huc = svi_df %>% group_by(`...1`) %>% 
  mutate(pct=pop/sum(pop)*100)

svi_all = svi_df %>%
  group_by(svi,version,threshold) %>% summarise(pop=sum(pop)) %>% ungroup %>%
  group_by(version,threshold) %>% mutate(pct=pop/sum(pop)*100) %>% ungroup

svi_present = svi_all %>% filter(version=='present') %>% mutate(baseline=pop)
svi_climate_change = svi_all%>% filter(version!='present')%>%
  left_join(dplyr::select(svi_present,c(svi,threshold,baseline))) %>%
  group_by(version,threshold) %>%
  mutate(pop_delta = abs(pop-baseline), pct_delta = pop_delta/sum(pop_delta)*100) %>% ungroup
# svi_climate_change

# reorganize data for plotting
svi_data_plot = svi_climate_change %>% transmute(svi,version,threshold,pop=pop_delta,pct=pct_delta) %>%
  bind_rows(dplyr::select(svi_present,-baseline)) %>%
  bind_rows(add_column(svi_bg_all,version="background",threshold=0))
# svi_data_plot

# inequality index
auc = function(data){
  area = 0
  last = 0
  for(d in data){
    sub_area = 0.25*(last+d)/2
    area = area + sub_area
    last = d
  }
  return(area)
}

inequality_relative = function(data,ref){
  ref_auc = ref %>% cumsum %>% auc
  data_auc = data %>% cumsum %>% auc
  output = (ref_auc-data_auc)/ref_auc
  return(output)
}

inequality_absolute = function(data){
  data_auc = data %>% cumsum %>% auc
  output = 1-2*data_auc/100
  return(output)
}

# SII_absolute of background population
ref = svi_data_plot %>% filter(version=='background') %>% pull(pct)
inequality_absolute(ref)

calcSII = function(data,depth,ref){
  foreach(v=unique(data$version),.combine=bind_rows)%do%{
    if (v=='background') df = data %>% filter(version==v) %>% pull(pct)
    else df = data %>% filter(version==v&threshold==depth) %>% pull(pct)
    SII_a = inequality_absolute(df) %>% round(3)
    SII_r = inequality_relative(df,ref)%>% round(3)
    return(tibble(version=v,SII_a,SII_r))
  }
}

version_lbl = c('background'='Background','present'='Present','p7'='\u0394 Past 7%','p14'='\u0394 Past 14%',
                'f7'='\u0394 Future 7%','f14'='\u0394 Future 14%')

# Prepare SVI_SII table for figure 5
prepSVItbl = function(df,depth,ref,subtitle){
  tbl_theme = ttheme(base_style = "light",base_size = 9,padding = unit(c(1, 2), "mm"))
  df_sii = calcSII(df,depth,ref)
  df %>% filter(threshold==depth|threshold==0) %>% 
    transmute(svi,Scenario=version,pct=round(pct,2)) %>%
    pivot_wider(names_from=svi,values_from=pct)%>%
    left_join(df_sii,by=c('Scenario'='version'))%>%
    transmute(Scenario=version_lbl[Scenario],`%Least`=Lowest,`%Less`=Medium_low,`%More`=Medium_high,`%Most`=Highest,SII_a,SII_r) %>%
    ggtexttable(rows = NULL,theme = tbl_theme) %>%
    tab_add_title(text = subtitle, face = "bold")
}
plot_df_05 = prepSVItbl(svi_data_plot,0.5,ref,"All flood exposure")
plot_df_3 = prepSVItbl(svi_data_plot,3,ref,"Deep flood exposure")

# Prepare concentration curves for figure 5
pct2cump = function(df,v,th){
  c(0,df%>%filter(version==v&threshold==th)%>%pull(pct)%>%cumsum)/100
}
concentrationCurve = function(df,threshold){
  tibble(svi=c(0,0.25,0.5,0.75,1),
         background=pct2cump(df,'background',0),
         present=pct2cump(df,'present',threshold),
         p7=pct2cump(df,'p7',threshold),
         p14=pct2cump(df,'p14',threshold),
         f7=pct2cump(df,'f7',threshold),
         f14=pct2cump(df,'f14',threshold),
  ) %>% pivot_longer(!svi) %>%
    mutate(name=factor(name,levels=c('background','present','p7','p14','f7','f14')))
}
plotSII = function(df,title){
  version_col = c('background'='grey30','present'='grey50','p7'='dodgerblue1','p14'='dodgerblue4','f7'='coral1','f14'='coral4')
  version_lbl = c('background'='Background','present'='Present','p7'='\u0394 Past 7%','p14'='\u0394 Past 14%',
                  'f7'='\u0394 Future 7%','f14'='\u0394 Future 14%')
  ggplot(df)+
    geom_line(aes(x=svi,y=value,color=name,group=name))+
    geom_segment(aes(x=0,y=0,xend=1,yend=1),linetype=2)+
    annotate("text",label=title,x=0,y=1,hjust=0)+
    labs(x='SVI',y='Cumulative proportion',color='Scenario')+
    scale_color_manual(values=version_col,labels=version_lbl)
}

df_concentration_05 = concentrationCurve(svi_data_plot,0.5)
df_concentration_3 = concentrationCurve(svi_data_plot,3)

# Figure 5
plot_ssi_05 = plotSII(df_concentration_05,'(a)')
plot_ssi_3 = plotSII(df_concentration_3,'(b)')
plot_ssi = ggarrange(plot_ssi_05, plot_df_05, plot_ssi_3, plot_df_3, 
                     ncol=2, nrow=2,widths = c(2, 3), 
                     common.legend = TRUE, legend="bottom",align='h')
plot_ssi
# ggarrange(plot_svi, plot_ssi, ncol=1, nrow=2,heights=c(3,4))
ggsave(path(plot_folder,'svi_ssi.png'),w=6,h=5)

################################################################
# Validation
################################################################
hwm = read_csv(path(base_folder,'data/flood/validation/hwm_rift.csv'))
# recall by domain
hwm %>% group_by(HUC4) %>% summarise(n=n(),recall=sum(rift>0.15)/n())
# overall recall
hwm %>% summarise(n=n(),recall=sum(rift>0.15)/n())
